### ISSUE TITLE
[Pre-processing algorithm] - Python LFR: No module named 'Numba.decorators': LFR will be unavailable

### ISSUE THREAD

**Issue by nikunjlad** [Trusted-AI/AIF360#213]
On running the example notebook: [demo_lfr.ipynb](https://github.com/Trusted-AI/AIF360/blob/master/examples/demo_lfr.ipynb), I get the following error:

```
WARNING:root:No module named 'numba.decorators': LFR will be unavailable. To install, run:
pip install 'aif360[LFR]'
<class 'aif360.datasets.adult_dataset.AdultDataset'>
(34189, 18)
1.0 0.0
['sex', 'race']
[array([1.]), array([1.])] [array([0.]), array([0.])]
['race', 'sex', 'Age (decade)=10', 'Age (decade)=20', 'Age (decade)=30', 'Age (decade)=40', 'Age (decade)=50', 'Age (decade)=60', 'Age (decade)=>=70', 'Education Years=6', 'Education Years=7', 'Education Years=8', 'Education Years=9', 'Education Years=10', 'Education Years=11', 'Education Years=12', 'Education Years=<6', 'Education Years=>12']
<IPython.core.display.Markdown object>
Difference in mean outcomes between unprivileged and privileged groups = -0.195439
<IPython.core.display.Markdown object>
Difference in mean outcomes between unprivileged and privileged groups = -0.192336
Traceback (most recent call last):
  File "/Users/nikunjlad/github/Bais-Fairness-Library/src/learn_fair_representation.py", line 77, in <module>
    main()
  File "/Users/nikunjlad/github/Bais-Fairness-Library/src/learn_fair_representation.py", line 73, in main
    TR = TR.fit(dataset_orig_train, maxiter=5000, maxfun=5000)
  File "/Users/nikunjlad/.virtualenvs/bias/lib/python3.6/site-packages/aif360/algorithms/transformer.py", line 27, in wrapper
    new_dataset = func(self, *args, **kwargs)
  File "/Users/nikunjlad/.virtualenvs/bias/lib/python3.6/site-packages/aif360/algorithms/preprocessing/lfr.py", line 105, in fit
    self.learned_model = optim.fmin_l_bfgs_b(lfr_helpers.LFR_optim_obj, x0=model_inits, epsilon=1e-5,
NameError: name 'lfr_helpers' is not defined
```

**Comment by nikunjlad** [comment]
The part of the code that needs attention is not present in this library. In fact, the code with pip install has Numba decorators in it, which is not the case in the code provided in this Github. Hence I am closing, this for now.
